//#ifndef COBRA_TRANSPORT_CONSTANTS_H
//#define COBRA_TRANSPORT_CONSTANTS_H
//
//#define COBRA_TRANSPORT_PACKET_HEADER_LEN 2
//
//#define COBRA_TRANSPORT_OK 0
//#define COBRA_TRANSPORT_DNS_ERR 1
//#define COBRA_TRANSPORT_CONNECTION_ERR 2
//
//#endif //COBRA_TRANSPORT_CONSTANTS_H